-- liquibase formatted sql

-- changeset nithiwut:007-enable-asset-price-history

ALTER TABLE asset_price RENAME COLUMN asset_price TO price;
ALTER TABLE asset_price RENAME COLUMN price_date TO priced_at;
ALTER TABLE asset_price ALTER COLUMN priced_at TYPE TIMESTAMP USING priced_at::TIMESTAMP;
ALTER TABLE asset_price DROP CONSTRAINT asset_price_pkey;
ALTER TABLE asset_price ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE asset_price ADD CONSTRAINT pk_asset_price PRIMARY KEY (id);
ALTER TABLE asset_price ADD CONSTRAINT chk_asset_price_positive CHECK (price > 0);

CREATE INDEX idx_asset_price_latest
    ON asset_price(asset_id, priced_at DESC, id DESC);

-- rollback DROP INDEX idx_asset_price_latest;
-- rollback ALTER TABLE asset_price DROP CONSTRAINT chk_asset_price_positive;
-- rollback DELETE FROM asset_price older USING asset_price newer WHERE older.asset_id = newer.asset_id AND (older.priced_at < newer.priced_at OR (older.priced_at = newer.priced_at AND older.id < newer.id));
-- rollback ALTER TABLE asset_price DROP CONSTRAINT pk_asset_price;
-- rollback ALTER TABLE asset_price ADD CONSTRAINT asset_price_pkey PRIMARY KEY (asset_id);
-- rollback ALTER TABLE asset_price DROP COLUMN id;
-- rollback ALTER TABLE asset_price ALTER COLUMN priced_at TYPE DATE USING priced_at::DATE;
-- rollback ALTER TABLE asset_price RENAME COLUMN priced_at TO price_date;
-- rollback ALTER TABLE asset_price RENAME COLUMN price TO asset_price;
